In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [2]:
df = pd.read_csv("hiring.csv")

In [3]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [4]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [5]:
df.experience=df.experience.fillna('zero').astype(str)
df.experience=df.experience.apply(w2n.word_to_num)

In [6]:
df["test_score(out of 10)"].mean()

7.857142857142857

In [7]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(df["test_score(out of 10)"].mean())
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [8]:
xtrain = df.drop("salary($)",axis="columns")
xtrain

experience  test_score(out of 10)  interview_score(out of 10)
0           0               8.000000                           9
1           0               8.000000                           6
2           5               6.000000                           7
3           2              10.000000                          10
4           7               9.000000                           6
5           3               7.000000                          10
6          10               7.857143                           7
7          11               7.000000                           8

In [9]:
ytrain = df["salary($)"]
ytrain

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [12]:
reg = linear_model.LinearRegression()
reg.fit(xtrain,ytrain)

LinearRegression()

In [13]:
reg.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [14]:
reg.intercept_

17237.33031372721

In [15]:
reg.predict([[2, 9, 6]])

array([53290.89255945])

In [16]:
reg.predict([[12, 10, 10]])

array([92268.07227784])